apiVersion: v1
kind: Service
metadata:
  name: vote-app
  namespace: three-tier
spec:
  selector:
    app: vote-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
