---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: voteapp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/voteapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voteapp-pvc
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
