apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: three-tier
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
