apiVersion: v1
kind: Service
metadata:
  name: result-app
  namespace: three-tier
  annotations:
  #  alb.ingress.kubernetes.io/healthcheck-path: /result
spec:
  selector:
    app: result-app
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  type: NodePort
